In [3]:
import numpy as np 
array = np.array([1,5,5])
#To check data type store in array
print(array.dtype)
#To check number of dimensions
print(array.ndim)
#To check shape
print(array.shape)
#Creating array of number
new_array = np.arange(1,10, .5)
new_array = new_array.reshape(2,9)
new_array = np.linspace(1,10,9)
print(new_array)
#To create array of random numbers
print(np.random.rand(2,3))


int32
1
(3,)
[ 1.     2.125  3.25   4.375  5.5    6.625  7.75   8.875 10.   ]
[[0.09366029 0.28387189 0.08486577]
 [0.56316793 0.24782042 0.42078526]]


In [31]:
#Broadcasting
A = np.arange(16).reshape(4, 4)
b = np.arange(4)
print(A)
print(b)
A+b

print(A+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[0 1 2 3]
[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]
 [12 14 16 18]]
